# We copy the theme folder from THIS action's repo into the book's workspace

name: "Abhi's custom mdBook theme"
description: "Injects a custom theme"

runs:
  using: "composite"
  steps:
    - name: Inject custom theme
      run: |
        rm -rf ./theme
        cp -r ${{ github.action_path }}/theme ./theme
        rm -rf ./extras
        cp -r ${{ github.action_path }}/extras ./extras
      shell: bash

    - name: Install mdBook
      env:
          MDBOOK_VERSION: 0.5.4
          LAST_CHANGED_VERSION: 0.4.0
      run: |
        mkdir -p bin
        curl -sSL https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        curl -sSL https://github.com/badboy/mdbook-last-changed/releases/download/v${LAST_CHANGED_VERSION}/mdbook-last-changed-v${LAST_CHANGED_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
        echo "$PWD/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Build mdBook
      run: mdbook build
      shell: bash
