[book]
authors = ["Abhinandh S"]
language = "en"
src = "src"
title = "Abhi's guide to ..."

[output.html]
site-url = "/mdbook-theme/"
git-repository-url = "https://github.com/abhinandh-s/mdbook-theme"

additional-css = [
  "extras/css/comment-box.css",
  "extras/css/custom-callouts.css",
  "extras/css/last-changed.css",
]
additional-js = [
  "extras/js/custom-callouts.js",
  "extras/js/last-changed.js",
  "extras/js/comment-box.js",
]

[preprocessor.last-changed]
command = "mdbook-last-changed"
renderer = ["html"]

