# To get started with mdBook see: https://rust-lang.github.io/mdBook/index.html

name: Deploy mdBook site to Pages

on:
  push:
    branches: ["master"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.5.4
      LAST_CHANGED_VERSION: 0.4.0
    steps:
      - uses: actions/checkout@v4

      - name: Install Last Changed
        run: |
          curl -sSL https://github.com/badboy/mdbook-last-changed/releases/download/v${LAST_CHANGED_VERSION}/mdbook-last-changed-v${LAST_CHANGED_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin

      - name: Install mdBook
        run: |
          mkdir -p bin
          curl -sSL https://github.com/rust-lang/mdBook/releases/download/v${MDBOOK_VERSION}/mdbook-v${MDBOOK_VERSION}-x86_64-unknown-linux-gnu.tar.gz | tar -xz --directory=bin
          echo "$PWD/bin" >> "$GITHUB_PATH"
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Build with mdBook
        run: mdbook build

      #- name: Delete Theme Directory
      #  run: rm -rf theme

      #- name: Generate Theme Directory
      #  run: mdbook init --theme

      - name: Commit generated files
        uses: stefanzweifel/git-auto-commit-action@v5
        continue-on-error: true 
        with:
          commit_message: "chore: compile rust to wasm [skip ci]"
          add_options: '-f'
          file_pattern: 'theme/' 

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
